[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[prune]
  go-tests = true
  unused-packages = true
